"""empty message

Revision ID: d1d2f507570c
Revises: 
Create Date: 2020-05-27 13:38:02.046968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d2f507570c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logindate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logindate', sa.DateTime(), nullable=False),
    sa.Column('signin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['signin_id'], ['signin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=False),
    sa.Column('avator', sa.String(length=255), nullable=False),
    sa.Column('signin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['signin_id'], ['signin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_title', sa.String(length=255), nullable=False),
    sa.Column('p_main', sa.String(length=3000), nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['u_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea', sa.String(length=3000), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['p_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=3000), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['i_id'], ['ideas.id'], ),
    sa.ForeignKeyConstraint(['p_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('ideas')
    op.drop_table('problems')
    op.drop_table('users')
    op.drop_table('logindate')
    op.drop_table('signin')
    # ### end Alembic commands ###
